routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/soldiers' , 'SoldierController');

resources/views/layouts/includes/navbar.blade.php
       <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="{{ asset('images/site/logo2.jpg') }}" width="70" height="70">
                    <span class="long--text me-2">{{ 'البرنامج الالكتروني لاداره الامن و التحريات' }}</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

resources/views/layouts/includes/sidebar.blade.php
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <h2>لوحه التحكم</h2>
    </div>
    <ul class="sidebar-nav">
      <li class="active">
        <a href="{{route('home')}}"><i class="fa fa-home"></i>الرئيسيه</a>
      </li>
      <li>
        <a href="{{route('soldiers.index')}}"><i class="fa fa-users"></i>القوات</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-file-alt"></i>التقارير</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-comments"></i>الرسائل</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-file"></i>المستندات</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-cogs"></i>الاعدادت</a>
      </li>
    </ul>
  </aside>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const navbar = document.querySelector('.navbar');
    const sidebar = document.querySelector('#sidebar-wrapper');
    const navbarHeight = navbar.innerHeight;
    window.onscroll = () => {
      stickySidebar(window.scrollY, navbar.offsetHeight)
    }

    function stickySidebar(YAxis, navHeight) {
      YAxis >= navHeight + 4 ?
        sidebar.classList.add('sticky')
        : sidebar.classList.remove('sticky')
    }
  })
  

  
</script>